In [1]:
from kemeny_hamming_embeddings import KemenyEmbed, KemenyEmbed_no_offset_unisign, HammingEmbed, vectorize_hamming_labels
from misc_functions import ranking_format_sorted, ranking_format

#### Kemeny

In [5]:
KemenyEmbed_no_offset_unisign(ranking_format_sorted("a>d>b>c"))

array([1., 1., 1., 1., 0., 0.])

#### Hamming

In [2]:
import numpy as np

In [3]:
def HammingEmbed_2(sigma):    
    phi=np.zeros((len(sigma),len(sigma)))
    for i in sigma:
        j=tuple(sigma).index(i)
        phi[j,i]+=1
    return phi        

In [5]:
sig = ranking_format_sorted("a>c>b")
print(sig)
print("Hamming_paper \n", HammingEmbed(sig))
print("Hamming_new \n", HammingEmbed_2(sig))


[0, 2, 1]
Hamming_paper 
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Hamming_new 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [6]:
sig = ranking_format_sorted("a>c>d>b")
print(sig)
print("Hamming_paper \n", HammingEmbed(sig))
print("Hamming_new \n", HammingEmbed_2(sig))

[0, 3, 1, 2]
Hamming_paper 
 [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
Hamming_new 
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [7]:
sig = ranking_format_sorted("a>d>b>c")
print(sig)
print("Hamming_paper \n", HammingEmbed(sig))
print("Hamming_new \n", HammingEmbed_2(sig))

[0, 2, 3, 1]
Hamming_paper 
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
Hamming_new 
 [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
